version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region eu-central-1 --no-include-email)
    - REPOSITORY_URI=348099934012.dkr.ecr.eu-central-1.amazonaws.com/kilt/prototype-chain
    - IMAGE_TAG=$(cat Cargo.toml | grep version | head -1 | sed "s/[',]//g" | cut -d "=" -f2 | tr -d '[[:space:]]')
    - docker pull $REPOSITORY_URI:latest || true
  build:
    commands:
    - echo Run 'build / test'
    - echo "REPOSITORY_URI=$REPOSITORY_URI"
    - echo "IMAGE_TAG=$IMAGE_TAG"
    - docker build --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
    - echo 'build / test' successful!
