version: 0.2

phases:
  build:
    commands:
    - echo Run 'build / test'
    - docker build --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
    - echo 'build / test' successful!
