[package]
authors = ['Parity Technologies <admin@parity.io>']
edition = '2018'
name = 'mashnet-node-runtime-wasm'
version = '1.0.0'
[dependencies.mashnet-node-runtime]
default-features = false
path = '..'

[features]
default = []
std = ['mashnet-node-runtime/std']

[workspace]
members = []

[lib]
crate-type = ['cdylib']
[profile.release]
lto = true
panic = 'abort'
