[package]
authors = ["KILT <info@kilt.io>"]
edition = "2018"
name = "mashnet-node-runtime"
version = "0.24.0"

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dependencies]
# kilt functionality
attestation = {default-features = false, path = "../../pallets/attestation"}
kilt-launch = {default-features = false, path = "../../pallets/kilt-launch"}
ctype = {default-features = false, path = "../../pallets/ctype"}
delegation = {default-features = false, path = "../../pallets/delegation"}
did = {default-features = false, path = "../../pallets/did"}
kilt-primitives = {path = "../../primitives", default-features = false}

# kilt specific
pallet-vesting = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "master"}

# Benchmarking
frame-benchmarking = {git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "master"}
frame-system-benchmarking = {git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "master"}
hex-literal = {version = "0.3.1", optional = true}

[dependencies.aura]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-aura"
version = "3.0.0"

[dependencies.authorship]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-authorship"
version = "3.0.0"

[dependencies.balances]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-balances"
version = "3.0.0"

[dependencies.bitflags]
default-features = false
version = "1.2.1"

[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "2.0.0"

[dependencies.executive]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "frame-executive"
version = "3.0.0"

[dependencies.frame-support]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.frame-system]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.frame-system-rpc-runtime-api]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.grandpa]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-grandpa"
version = "3.0.0"

[dependencies.pallet-indices]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.pallet-transaction-payment]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.pallet-transaction-payment-rpc-runtime-api]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.randomness-collective-flip]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-randomness-collective-flip"
version = "3.0.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.session]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-session"
version = "3.0.0"

[dependencies.sp-api]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-arithmetic]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-block-builder]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-consensus-aura]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "0.9.0"

[dependencies.sp-core]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-inherents]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-io]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-offchain]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-runtime]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-session]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-std]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-transaction-pool]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sp-version]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
version = "3.0.0"

[dependencies.sudo]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-sudo"
version = "3.0.0"

[dependencies.timestamp]
branch = "master"
default-features = false
git = "https://github.com/paritytech/substrate"
package = "pallet-timestamp"
version = "3.0.0"

[features]
default = ["std"]
runtime-benchmarks = [
  "attestation/runtime-benchmarks",
  "ctype/runtime-benchmarks",
  "delegation/runtime-benchmarks",
  "did/runtime-benchmarks",
  "frame-benchmarking",
  "frame-system-benchmarking",
  "hex-literal",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "kilt-launch/runtime-benchmarks",
  "balances/runtime-benchmarks",
  "pallet-indices/runtime-benchmarks",
  "pallet-vesting/runtime-benchmarks",
  "timestamp/runtime-benchmarks",
]
std = [
  "attestation/std",
  "kilt-launch/std",
  "ctype/std",
  "did/std",
  "delegation/std",
  "pallet-indices/std",
  "grandpa/std",
  "aura/std",
  "balances/std",
  "codec/std",
  "sp-consensus-aura/std",
  "executive/std",
  "sp-core/std",
  "sp-std/std",
  "sp-io/std",
  "sp-runtime/std",
  "randomness-collective-flip/std",
  "serde",
  "sudo/std",
  "session/std",
  "frame-support/std",
  "frame-system/std",
  "timestamp/std",
  "sp-version/std",
  "sp-block-builder/std",
  "pallet-transaction-payment/std",
  "sp-transaction-pool/std",
  "sp-offchain/std",
  "sp-arithmetic/std",
  "sp-api/std",
  "sp-inherents/std",
  "sp-session/std",
  "frame-system-rpc-runtime-api/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "kilt-primitives/std",
  "pallet-vesting/std",
]
